[unstable]
build-std-features = ["compiler-builtins-mem"] # This enables the mem feature of the compiler_builtins crate

# The unstable.build-std configuration key requires at least the Rust nightly from 2020-07-15.
build-std = ["core", "compiler_builtins"] # This tells cargo that it should recompile the core and compiler_builtins libraries.

# cargo +nightly build --target x86_64-blog_os.json
[build]
target = "x86_64-blog_os.json"

# cargo run
[target.'cfg(target_os = "none")']
runner = "bootimage runner" # It links the given executable with the project’s bootloader dependency and then launches QEMU.
